api:
  version: "v1"
  
http:
  listener:
    path: "/a-flights-sa/api/${api.version}"
     
db:
  mysql:
    host: "mudb.mule-training.com"
    port: "3306"
    user: "mule"
    password: "mule"
    database: "training"

ampq:
  host: "localhost"
  port: "5672"
  user: "AndriiDev"
  password: "qwerty12345"
